import React from "react";
import { Download, FileText } from "lucide-react";

interface ExportRecord {
  id: number;
  report_name: string;
  generated_at: string;
  format: string;
  generated_by: string;
  file_path: string;
}

interface RecentExportsTableProps {
  exports: ExportRecord[];
  onDownload: (exportId: number) => void;
}

export function RecentExportsTable({
  exports,
  onDownload,
}: RecentExportsTableProps) {
  const getFormatBadge = (format: string) => {
    const colors: Record<string, string> = {
      xlsx: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-300 border-green-200 dark:border-green-800",
      pdf: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300 border-red-200 dark:border-red-800",
      docx: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300 border-blue-200 dark:border-blue-800",
    };
    return colors[format] || colors["pdf"];
  };

  const formatDate = (dateStr: string) => {
    const date = new Date(dateStr);
    return date.toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    });
  };

  return (
    <div className="mt-12">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-slate-900 dark:text-white text-lg font-bold">
          Recent Exports
        </h2>
        <a
          href="#"
          className="text-sm text-primary hover:text-blue-600 font-medium flex items-center gap-1"
        >
          View All History
          <span className="text-[16px]">→</span>
        </a>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 dark:text-slate-400 uppercase bg-slate-50 dark:bg-slate-800 border-b border-slate-200 dark:border-slate-700">
              <tr>
                <th className="px-6 py-3 font-medium">Report Name</th>
                <th className="px-6 py-3 font-medium">Date Generated</th>
                <th className="px-6 py-3 font-medium">Format</th>
                <th className="px-6 py-3 font-medium">Generated By</th>
                <th className="px-6 py-3 font-medium text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {exports.map((exp) => (
                <tr
                  key={exp.id}
                  className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition-colors"
                >
                  <td className="px-6 py-4 font-medium text-slate-900 dark:text-white">
                    <div className="flex items-center gap-3">
                      <FileText className="w-4 h-4 text-slate-400" />
                      {exp.report_name}
                    </div>
                  </td>
                  <td className="px-6 py-4 text-slate-500 dark:text-slate-400">
                    {formatDate(exp.generated_at)}
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded text-xs font-medium border ${getFormatBadge(exp.format)}`}
                    >
                      .{exp.format}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-slate-500 dark:text-slate-400">
                    {exp.generated_by}
                  </td>
                  <td className="px-6 py-4 text-right">
                    <button
                      onClick={() => onDownload(exp.id)}
                      className="text-primary hover:text-blue-700 font-medium text-xs flex items-center gap-1 ml-auto"
                    >
                      <Download className="w-3 h-3" />
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
